-- v8.4.5: jednorazowe rabaty na osobę + adres
create table if not exists public.promo_redemptions (
  id bigint generated by default as identity primary key,
  promo_code text not null,
  discount_percent integer not null check (discount_percent between 1 and 100),
  identity_hash text not null,
  order_id bigint null,
  created_at timestamptz not null default now()
);

-- Jedna osoba + adres może dostać rabat tylko raz, niezależnie od kodu.
create unique index if not exists promo_redemptions_identity_unique
  on public.promo_redemptions(identity_hash);

alter table public.promo_redemptions enable row level security;
revoke all on table public.promo_redemptions from anon, authenticated;
