-- DIETY v3 — uruchom w Supabase SQL Editor.
-- Uwaga: skrypt zakłada używanie Supabase Auth.

create type public.app_role as enum ('admin', 'kitchen', 'courier');
create type public.kitchen_status as enum ('todo', 'prep', 'ready', 'issued');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'courier',
  route_code text,
  created_at timestamptz not null default now()
);

create table public.diets (
  id bigint generated by default as identity primary key,
  client_name text not null,
  diet_name text not null,
  kcal integer not null check (kcal > 0),
  bags integer not null default 1 check (bags > 0),
  route_code text not null,
  start_date date not null,
  end_date date not null,
  kitchen_status public.kitchen_status not null default 'todo',
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint valid_date_range check (end_date >= start_date)
);

alter table public.profiles enable row level security;
alter table public.diets enable row level security;

-- Każdy zalogowany użytkownik może odczytać swój profil.
create policy "read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

-- Administrator może odczytać wszystkie profile.
create policy "admin reads profiles"
on public.profiles for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Admin i kuchnia widzą wszystkie diety.
create policy "admin kitchen read diets"
on public.diets for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','kitchen')
  )
);

-- Kurier widzi wyłącznie pozycje wydane na jego trasę i aktywne w danym dniu.
create policy "courier reads issued active route"
on public.diets for select
to authenticated
using (
  kitchen_status = 'issued'
  and current_date between start_date and end_date
  and route_code = (
    select p.route_code from public.profiles p where p.id = auth.uid()
  )
);

-- Tylko administrator może tworzyć/usuwać diety.
create policy "admin inserts diets"
on public.diets for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy "admin deletes diets"
on public.diets for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Admin i kuchnia mogą aktualizować status/rekord.
create policy "admin kitchen update diets"
on public.diets for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','kitchen')
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin','kitchen')
  )
);

-- Automatycznie tworzy profil przy rejestracji nowego użytkownika.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data ->> 'full_name', 'courier');
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Przykładowe dane (opcjonalnie):
insert into public.diets
(client_name,diet_name,kcal,bags,route_code,start_date,end_date,kitchen_status,notes)
values
('Anna Kowalska','Standard',1500,1,'A',current_date - 3,current_date + 20,'ready','Bez cebuli'),
('Piotr Nowak','Sport',2500,2,'A',current_date,current_date + 14,'todo','Dodatkowy shake'),
('Kasia Zielińska','Keto',1800,1,'B',current_date,current_date + 30,'prep','Bez nabiału');
